### ISSUE TITLE
Allow for different decimal separators.

### ISSUE THREAD

**Issue by mineminemine** [thiagoprz/ionic-currency-mask#2]
Some countries use different separators.
Currently it's (decimal ","; thousand ".") but some countries use (decimal "."; thousand ",").

**Comment by thiagoprz** [comment]
Hi @mineminemine , thanks for the input, i'm adding a new branch for us to test it using input attributes. Please pull or install the library using the "allow_different_separators" branch, in it you will notice two Attribute decorators expecting "decimal" and "thousand" properties. 
Basically the library will use  those attributes to define decimal and thousand separators.

Usage:

`
<ion-input decimal="." thousand="," [(ngModel)]="price" maxlength="18" type="tel" placeholder="0.00"></ion-input>
`

**Comment by mineminemine** [comment]
Hi @thiagoprz , thanks for the help and I just managed to get done testing the new branch and the two attributes works fine.
However, the masking process is slightly botched in the regex part since they are still targeting specific characters.
`value = value.replace(/([0-9]{3}).([0-9]{2}$)/g, this.thousand + '$1' + this.decimal + '$2');`
and
`value = value.replace(/([0-9]{3}),([0-9]{3}).([0-9]{2}$)/g, this.thousand + '$1' + this.thousand + '$2' + this.decimal + '$3');`

Both the regex part above targets the , and . where the thousand and decimal separators are different.
Example: /([0-9]{3}),([0-9]{3}).([0-9]{2}$)/g does not work on 600,000.50 since the separators are the other way around.

**Comment by mineminemine** [comment]
One possible solution to the problem is to use RegExp like so:

```
        if (value.length > 6) {
            var regex = new RegExp("([0-9]{3})" + this.decimal + "([0-9]{2}$)", "g");
            value = value.replace(regex, this.thousand + '$1' + this.decimal + '$2');
        }
        if (value.length > 10) {
            var regex = new RegExp("([0-9]{3})" + this.thousand + "([0-9]{3})" + this.decimal + "([0-9]{2}$)", "g");
            value = value.replace(regex, this.thousand + '$1' + this.thousand + '$2' + this.decimal + '$3');
        }
```

And maybe to place the new RegExp somewhere else? Instead of creating a new one every time? I'm not sure myself sorry

**Comment by mineminemine** [comment]
Solution 2, possibly the best solution as it also caters for a higher currency number and not limited to the _value.length > 10_ constraint:

```
    changeValue(event) {
        let value = event.target.value;
        if (value == '') {
            return;
        }
        value = value + '';
        value = parseInt(value.replace(/[\D]+/g, ''));
        value = value + '';
        value = value.replace(/([0-9]{2})$/g, this.decimal + '$1');
        var parts = value.toString().split(this.decimal);
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, this.thousand);
        value = parts.join(this.decimal);
        console.log(value);
        event.target.value = value;
        this.model.update.emit(value);
        return true;
    }
```
Achieve similar effect and will now also account for numbers way longer than >10. Eg: 60000000000000 will now be converted to 600,000,000,000.00 instead of the previous 6000000,000,000.00.

Also credits to Elias Zamaria at https://stackoverflow.com/questions/2901102/how-to-print-a-number-with-commas-as-thousands-separators-in-javascript for the original solution.
